apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-deployment
  labels:
    app: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - name: console
        image: showkevin/console
        args: ["show me the money"]
